---
title: "Data Cleaning Exercise"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(rvest)
library(readr)
library(dplyr)
library(janitor)
```

Load the species table
```{r}
webpage <- read_html("https://www.pwrc.usgs.gov/bbl/manual/speclist.cfm")

tbls <- html_nodes(webpage, "table") %>% 
    html_table(fill = TRUE)

species <- tbls[[1]] %>% 
    clean_names() %>% 
    select(alpha_code, common_name) %>% 
    mutate(alpha_code = tolower(alpha_code))
head(species)
```

Load the data
```{r}
predator_surveys <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A9ffec04c-7e2d-41dd-9e88-b6c2e8c4375e")
predator_surveys

nest_data <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A982bd2fc-4edf-4da7-96ef-0d11b853102d")
nest_data
```

Write a function that translates species codes into common names. 
```{r}
species_codes_to_names <- function(df, species) {
  output_df <- left_join(df, species, by = c("species" = "alpha_code"))
  return(output_df)
}
```

Use the function to add the common names
```{r}
predator_survey_names <- species_codes_to_names(predator_surveys, species)
predator_survey_names

nest_data_names <- species_codes_to_names(nest_data, species)
nest_data_names
```

Clean up and summarize
```{r}
predator_survey_names_clean <- predator_survey_names %>%
  group_by(year, common_name) %>% 
  summarise(pred_count = sum(count, na.rm = T), .groups = "drop") %>% 
  filter(!is.na(common_name))
predator_survey_names_clean

ggplot(predator_survey_names_clean, aes(x = year, y = pred_count, color = common_name)) +
  geom_line() +
  geom_point() +
  labs(x = "Year", y = "Number of Predators", color = "Species") +
  theme_bw()
```
```{r}
nest_data_names_clean <- nest_data_names %>% 
  group_by(common_name, year) %>% 
  summarise(total_predated = sum(number_eggs_predated, na.rm = T), .groups = "drop")%>% 
  filter(!is.na(common_name))

```

Calculate total number of predators across all species by year.

```{r}
pred_total <- predator_survey_names_clean %>% 
    group_by(year) %>% 
    summarise(pred_count = sum(pred_count, na.rm = T), .groups = "drop")
```

Join egg predation data to total predator data.
```{r}
nest_pred <- left_join(nest_data_names_clean, pred_total, by = "year")
nest_pred
```

Plot the number of eggs predated by total predators, faceted over species. 

```{r, fig.width=6, fig.height=12}
ggplot(nest_pred, aes(x = pred_count, y = total_predated)) +
    geom_point() +
    facet_wrap(~common_name, scales = "free_y", ncol = 2) +
    labs(x = "Number of Predators", y = "Number of Eggs Predated") +
    theme_bw()
```

