---
title: "Data Visualization"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(leaflet)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(scales)
```

```{r message=FALSE, warning=FALSE}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        return(esc)
    }
)

head(esc)
```

```{r}
annual_esc <- esc %>% 
  separate(sampleDate, into = c("year", "month", "day"), sep = "-") %>% 
  mutate(year = as.numeric(year)) %>% 
  group_by(year, Species, SASAP.Region) %>% 
  summarise(annual_total = sum(DailyCount), .groups = "drop") %>% 
  filter(Species %in% c("Sockeye", "Chum", "Coho", "Chinook", "Pink"))
head(annual_esc)
```
## Plotting

```{r}
ggplot(annual_esc, aes(x = Species, y = annual_total, fill = SASAP.Region))+
  geom_col()+
  theme_minimal()
```

```{r}
kodiak_esc <- annual_esc %>% 
  filter(SASAP.Region == "Kodiak")
  
my_theme <- theme_bw()+
  theme(legend.position = "bottom")

ggplot(kodiak_esc, aes(x = year, y = annual_total, color = Species))+
  geom_line()+
  geom_point()+
  scale_y_continuous(labels = comma)+
  labs(x = "Year", y = "Annual Escapement (num. fish)", title = "Kodiak Salmon Escapement")+
  my_theme
  
```

```{r}
ggplot(annual_esc, aes(x = year, y = annual_total, color = Species))+
  geom_line()+
  geom_point()+
  scale_y_continuous(labels = comma) +
  facet_wrap(~SASAP.Region)+
  labs(x = "Year", y = "Annual Escapement (num. fish)", title = "Kodiak Salmon Escapement")+
  my_theme
```

## Interactive tables

```{r}
locations <- esc %>% 
  distinct(Location, Latitude, Longitude) %>% 
  drop_na()
```

```{r}
datatable(locations)
```

