---
title: "Functions_lesson"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(roxygen2)
```

# Example without using functions

```{r}
airtemps <- c(212, 30.3, 78, 32)
celsius1 <- (airtemps[1]-32)*5/9
celsius2 <- (airtemps[2]-32)*5/9
celsius3 <- (airtemps[3]-32)*5/9
```


# Create a function to do the same thing

```{r}
fahr_to_celsius <- function(fahr) {
   celsius <- (fahr-32)*5/9
   return(celsius)
}
```

```{r}
celsius4 <- fahr_to_celsius(airtemps[1])
celsius4
celsius1 == celsius4
```
```{r}
celsius <- fahr_to_celsius(airtemps)
celsius
```

# convert back from celsius to fahrenheit

```{r}
#' Converts Celsius to Fahrenheit
#' 
#' This function takes scalar or vector values in degrees Celsisu
#' and returns values in Fahrenheit
#'
#' @param celsius the input temperature in degrees Celsius
#'
celsius_to_fahr <- function(celsius) {
  fahr <- (celsius*9/5) + 32
  return(fahr)
}
```

```{r}
result <- celsius_to_fahr(celsius)
result
result == airtemps
```



# Test function


# Document function